- name: Enable passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"

- name: Add user account
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    groups: sudo
    append: yes
  with_items: users

- name: Add user SSH keys
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  with_subelements:
    - users
    - authorized_keys

- name: ec2 facts
  action: ec2_facts

- name: facts
  action: setup

- name: update apt
  apt:
    update_cache: yes

- name: Install pip
  apt:
    name: python-pip

- name: Install python deps
  apt:
    name: python-dev

- name: Install python dependencies
  pip:
    name: '{{item}}'
  with_items:
    - awscli
    - boto
    - credstash
