- name: workaround pad.lv/1518457
  file:
    path: /etc/udev/rules.d/40-vm-hotadd.rules
    src: /dev/null
    state: link

- name: Enable passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"

- name: Add user account
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    groups: sudo
    append: yes
  with_items: '{{users}}'

- name: Add user SSH keys
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  with_subelements:
    - '{{users}}'
    - authorized_keys

- name: github known_hosts
  known_hosts:
    host: github.com
    path: /etc/ssh/ssh_known_hosts
    key: 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
    state: present

- name: ec2 facts
  action: ec2_facts

- name: facts
  action: setup

- name: set hostname
  hostname:
    name: '{{role}}-{{ansible_ec2_instance_id}}'
  when: 'role is defined'

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "127.0.0.1 {{role}}-{{ansible_ec2_instance_id}}"
  when: 'role is defined'

- name: update apt
  apt:
    update_cache: yes
    upgrade: dist

- name: Install packages
  apt:
    name: '{{item}}'
  with_items:
    - python-pip
    - python-dev
    - git

- name: Install python dependencies
  pip:
    name: '{{item}}'
  with_items:
    - awscli
    - boto
    - credstash

- name: download gof3r
  get_url:
    url: https://github.com/rlmcpherson/s3gof3r/releases/download/v0.5.0/gof3r_0.5.0_linux_amd64.tar.gz
    dest: /var/cache/gof3r_0.5.0_linux_amd64.tar.gz

- name: unpack gof3r
  unarchive:
    src: /var/cache/gof3r_0.5.0_linux_amd64.tar.gz
    copy: no
    dest: /var/cache/
    creates: /var/cache/gof3r_0.5.0_linux_amd64

- name: go3fr symlink
  file:
    path: /usr/local/bin/gof3r
    state: link
    src: /var/cache/gof3r_0.5.0_linux_amd64/gof3r

- name: copy lifecycle helpers
  copy:
    src: '{{item}}'
    dest: '/usr/local/bin/{{item}}'
    mode: 0755
  with_items:
    - complete-lifecycle-event
    - find-lifecycle-event
