- name: Enable passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"

- name: Add user account
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    groups: sudo
    append: yes
  with_items: users

- name: Add user SSH keys
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  with_subelements:
    - users
    - authorized_keys

- name: ec2 facts
  action: ec2_facts

- name: facts
  action: setup

- name: set hostname
  hostname:
    name: '{{role}}-{{ansible_ec2_instance_id}}'

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "127.0.0.1 {{role}}-{{ansible_ec2_instance_id}}"

- name: update apt
  apt:
    update_cache: yes

- name: Install pip
  apt:
    name: python-pip

- name: Install python deps
  apt:
    name: python-dev

- name: Install python dependencies
  pip:
    name: '{{item}}'
  with_items:
    - awscli
    - boto
    - credstash

- name: download gof3r
  get_url:
    url: https://github.com/rlmcpherson/s3gof3r/releases/download/v0.5.0/gof3r_0.5.0_linux_amd64.tar.gz
    dest: /var/cache/gof3r_0.5.0_linux_amd64.tar.gz

- name: unpack gof3r
  unarchive:
    src: /var/cache/gof3r_0.5.0_linux_amd64.tar.gz
    copy: no
    dest: /var/cache/
    creates: /var/cache/gof3r_0.5.0_linux_amd64

- name: go3fr symlink
  file:
    path: /usr/local/bin/gof3r
    state: link
    src: /var/cache/gof3r_0.5.0_linux_amd64/gof3r
