---
- name: letsencrypt dependencies
  apt:
    name: '{{item}}'
  with_items:
    - dialog
    - libaugeas0
    - libssl-dev
    - libffi-dev
    - ca-certificates

- name: install letsencrypt
  pip:
    name: letsencrypt

- name: Add letsencrypt user
  user:
    name: letsencrypt
    shell: /bin/bash
    append: yes

- name: letsencrypt directories
  file:
    path: '{{item}}'
    state: directory
    owner: letsencrypt
  with_items:
    - /etc/letsencrypt
    - /var/letsencrypt
    - /var/lib/letsencrypt
    - /var/log/letsencrypt

- name: credstash-store-certs
  copy:
    dest: /usr/local/bin/credstash-store-certs
    src: store-certs
    mode: 0755
    owner: root

- name: fetch letsencrypt account key
  shell: >-
    sudo -u letsencrypt "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" sh -c 'credstash -r us-west-2 get letsencrypt/accounts role=letsencrypt | openssl base64 -d | tar -C /etc/letsencrypt -xz'
  args:
    creates:
      /etc/letsencrypt/accounts
