- name: Add service user
  user:
    name: livegrep
    shell: /bin/bash
    append: yes

- name: configure root mail forwarding
  template:
    src: root-forward.j2
    dest: /root/.forward
    mode: 0644
    owner: root
    group: root

- name: download livegrep
  s3:
    bucket: livegrep
    object: builds/livegrep-{{livegrep_revision}}.tgz
    dest: /tmp/livegrep-{{livegrep_revision}}.tgz
    mode: get
    overwrite: false

- name: create livegrep build dir
  file:
    path: /home/livegrep/builds/
    state: directory

- name: unpack livegrep
  unarchive:
    src: /tmp/livegrep-{{livegrep_revision}}.tgz
    dest: /home/livegrep/builds/
    copy: false
    creates: /home/livegrep/builds/livegrep-{{livegrep_revision}}

- name: create livegrep deploy link
  file:
    path: /home/livegrep/deploy
    state: link
    src: builds/livegrep-{{livegrep_revision}}
