- name: Provision livegrep instances
  hosts: all
  sudo: yes
  gather_facts: false
  roles:
    - '{{role}}'
  vars:
    livegrep_revision: 0c36c4dc37
    livegrep_indexes:
      - id: linux
    livegrep_domain: livegrep.com
    livegrep_bucket: livegrep
    livegrep_mailto: nelhage@nelhage.com
    livegrep_timeout: 2500
