- name: livegrep config file
  template:
    src: livegrep.json.j2
    dest: /home/livegrep/livegrep.json
  notify: reload livegrep-web

- name: livegrep-web.service
  copy:
    src: livegrep-web.service
    dest: /etc/systemd/system/livegrep-web.service
    owner: root
    group: root

- name: start livegrep-web
  service:
    name: livegrep-web
    state: started

- name: livegrep nginx site
  template:
    dest: /etc/nginx/conf.d/livegrep.com.conf
    src: livegrep.com.conf.j2
  notify: reload nginx

- name: fetch livegrep certificates
  shell: |
    sudo -u letsencrypt sh -c '
      credstash -r us-west-2 get livegrep-web/certs/{{livegrep_domain}} \
        role=livegrep-web domain={{livegrep_domain}} | \
        openssl enc -d -a | \
        tar -C /etc/letsencrypt -xz
    '
  args:
    creates: '/etc/letsencrypt/live/{{livegrep_domain}}'

- name: livegrep-store-certs
  template:
    dest: /home/letsencrypt/livegrep-store-certs
    src: livegrep-store-certs.j2
    mode: 0755
    owner: root

- name: configure DNS
  route53:
    command: create
    type: A
    zone: livegrep.com
    record: beta.livegrep.com
    ttl: 60
    value: '{{ansible_ec2_public_ipv4}}'
    overwrite: true
